### ISSUE TITLE
Sync is Frozen - can't access wallet

### ISSUE THREAD

**Issue by mark54mco** [vechain/thor-sync#9] opened 2018-11-30 12:37 UTC
When I click my Sync Icon it opens Sync, as usual, but after making sync progress from about 75% to about 91%, it stopped and is frozen on Best Block 10,075,613, where it has been for several reboots and 15 days.
I expect it to complete the sync and open my wallet at 100%
I am running Mojave Version 10.14.1
Browser: Safari Version 12.0.1
There is nothing in the window that can be successfully clicked
I have Version 0.6.7 (0.6.7) of Sync. When I click "Check Update" in the menu it says, "There are no updates available."

**Comment by libotony** [comment] 2018-11-30 13:16
duplicate of #8 
@mark54mco can you take a look at my comment on that issue?

**Closed as completed** 2018-11-30 14:19 UTC
